version: '3.8'

services:
 
  backend:
    build: ./Event_Backend
    restart: on-failure
    # No ports mapped here! Only Nginx talks to backend.
    expose:
      - "8000"
    
 
    env_file:
      - .env  

    networks:
      - event_net

  
  nginx:
    image: nginx:alpine
    container_name: event_nginx
    restart: always
    ports:
      - "8000:80" # Host Port 8000 maps to Nginx Port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - event_net

  # 4. FRONTEND SERVICE
  frontend:
    build: ./event-mgmt-frontend
    container_name: event_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      # Frontend talks to Nginx (localhost:8000)
      VITE_API_URL: "http://localhost:8000/v1"
    networks:
      - event_net

networks:
  event_net:
    driver: bridge