name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Event_Backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./Event_Backend

    # GLOBAL ENV VARS
    env:
      NODE_ENV: 'test'
      PORT: '8000'
      
      # ✅ REAL SECRET (From GitHub Settings)
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
      # ✅ DUMMY SECRETS (To satisfy env.ts Zod rules)
      JWT_SECRET: '1234567890_dummy_secret_long_enough'
      REFRESH_SECRET: '1234567890_dummy_refresh_long_enough'
      JWT_EXPIRES_IN: '1d'

      CLIENT_URL: 'http://localhost:3000'
      GOOGLE_CALLBACK_URL: 'http://localhost:8000/auth/google/callback'
      
      GOOGLE_CLIENT_ID: 'dummy_google_id'
      GOOGLE_CLIENT_SECRET: 'dummy_google_secret'
      
      PAYPAL_CLIENT_ID: 'dummy_paypal_id'
      PAYPAL_CLIENT_SECRET: 'dummy_paypal_secret'
      PAYPAL_API: 'https://api-m.sandbox.paypal.com'
      
      KHALTI_SECRET_KEY: 'dummy_khalti_key'
      
      CLOUDINARY_CLOUD_NAME: 'dummy_cloud_name'
      CLOUDINARY_API_KEY: '1234567890'
      CLOUDINARY_API_SECRET: 'dummy_api_secret'

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Run Tests
      run: npm test